a=User.create(
  title:		'CEO',
  city:			'上海',
  id:			'10000',
  mobile:		'13916382071',
  user_name:		'乔吉',
  true_name:		'乔吉',
  :avatar => File.open(File.join(Rails.root, 'app', 'assets','images','george.jpeg')),
  email:		'cvsend@139.com',
  password:		'11111111',
  password_confirmation:'11111111',
  user_type:		'猎头',
  base_salary:		
            '10000',
  month_num:'13',
  bonus:		'50000',
  housing:	'10200',
  transport:'56000',
  birthday:	'1982-9-11',
  stock:		'',
  stock_num:	'',
  summaries_attributes:	{first:{content:'负责产品规格的制定和开发中的项目管理'},
	  		second:{content:'负责产品的coding,包括网页前端和后端的开发'},
			third: {content:'公司的日常管理'}},
  works_attributes:	
  			{first: 
    				{title:  'CEO',
	  			employer:'又招了电子商务',
				industry:'信息技术和人力资源',
				join_date:'2014-9-1',
				job_scope:'网站技术开发和公司日常管理',
				},
			second:{title:'经理',
				employer:'万宝盛华(Manpower)',
				industry:'人力资源',
				join_date:'2012-9-1',
				leave_date:'2014-8-31',
				job_scope:'开发猎头业务,带领猎头团队进行人才搜寻',
				}},
  educations_attributes:{first: {enter_school:'1997-9-1',
	  			leave_school:'2001-9-1',
				major:'计算机',
				degree:'本科',
				school:'浙江大学'}}
  			)


b=User.create(
  title:		'及时雨',
  city:			'郓城',
  id:			10001,
  mobile:		13916310001,
  user_name:		'宋江',
  true_name:		'宋江',
  :avatar => File.open(File.join(Rails.root, 'app', 'assets','images','宋江.jpg')),
  email:		'sj@ls.com',
  password:		'11111111',
  password_confirmation:'11111111',
  user_type:		'求职者',
  base_salary:		'10000',
  month_num:		'13',
  bonus:		'50000',
  housing:		'10200',
  transport:		'56000',
  birthday:		'1978-9-11',
  stock:		'股票',
  stock_num:		'1000',
  summaries_attributes:	{first:{content:'沉着冷静，神机妙算,足智多谋。例子：智取生辰纲、智取大名府 、智取文安县、 巧用双掌连环计、智赚玉麒麟、在二打曾头市中巧用“番犬伏窝”之计'},
	  		second:{content:'结交广泛，广纳贤才，知人善用。'},
			third: {content:'运筹帷幄之中，决胜千里之外。'}},
  works_attributes:	{first: {title:'及时雨',
	  			employer:'梁山',
				industry:'打家劫舍',
				join_date:'2000-9-01',
				leave_date:'2010-8-31',
				job_scope:'宋江，表字公明，排行第三，原籍为山东郓城县宋家村，江湖人称“及时雨”，又号“呼保义”。为他面黑身矮，人又唤他做黑宋江；又且于家大孝，为人仗义疏财，人皆称他做“孝义黑三郎”。',
				}},
  educations_attributes:{first: {enter_school:'1997-9-1',
	  			leave_school:'2001-9-1',
				major:'法学硕士',
				degree:'本科',
				school:'南京大学'}}
  			)

c=User.create(
  title:		'玉麒麟',
  city:			'大名府',
  id:			10002,
  mobile:		13916310002,
  user_name:		'卢俊义',
  true_name:		'卢俊义',
  :avatar => File.open(File.join(Rails.root, 'app', 'assets','images','卢俊义.jpg')),
  email:		'ljy@ls.com',
  password:		'11111111',
  password_confirmation:'11111111',
  user_type:		'求职者',
  password: 		1,
  password_confirmation:1,
  base_salary:		'10000',
  month_num:		'13',
  bonus:		'50000',
  housing:		'10200',
  transport:		'56000',
  birthday:		'1978-9-11',
  stock:		'股票',
  stock_num:		'1000',
  summaries_attributes:	{first:{content:'白玉麒麟，见之可爱。风尘太行，皮毛终坏。'},
			third: {content:'不该有福不享，无端好使枪棒，名震京师，结果被逼上梁山做了强盗。'}},
  works_attributes:	{first: {title:'玉麒麟',
	  			employer:'梁山',
				industry:'打家劫舍',
				join_date:'2000-9-01',
				leave_date:'2010-8-31',
				job_scope:'卢俊义是中国著名古典小说《水浒传》中的经典人物形象之一，绰号“玉麒麟”，武艺高强，棍棒天下无双，江湖人称“河北三绝”，祖居北京大名府（今河北省邯郸市大名县），仆人燕青。原本是河北大名府富商、大财主、员外，因为宋江喜爱他的才华，被诓上梁山，后来成为梁山第二首领。卢俊义和宋江一同受招安后，征讨了辽国、田虎、王庆、方腊，官至武功大夫、卢州安抚使。',
				}},
  educations_attributes:{first: {enter_school:'1997-9-1',
	  			leave_school:'2001-9-1',
				major:'法学硕士',
				degree:'本科',
				school:'南京大学'}}
  			)

d=User.create(
  title:		'智多星',
  city:			'菏泽',
  id:			10003,
  mobile:		13916310003,
  user_name:		'吴用',
  true_name:		'吴用',
  :avatar => File.open(File.join(Rails.root, 'app', 'assets','images','吴用.jpg')),
  email:		'wy@ls.com',
  password:		'11111111',
  password_confirmation:'11111111',
  user_type:		'求职者',
  base_salary:		'10000',
  month_num:		'13',
  bonus:		'50000',
  housing:		'10200',
  transport:		'56000',
  birthday:		'1978-9-11',
  stock:		'股票',
  stock_num:		'1000',
  summaries_attributes:	{first:{content:'沉着冷静，神机妙算，足智多谋。例子：智取生辰纲、智取大名府 、智取文安县、 巧用双掌连环计、智赚玉麒麟、在二打曾头市中巧用“番犬伏窝”之计'},
	                second:{content:'结交广泛，广纳贤才，知人善用。'},
			third: {content:'运筹帷幄之中，决胜千里之外。'},
			fourth:{content:'对宋江尽忠。'}},
  works_attributes:	{first: {title:'智多星',
	  			employer:'梁山',
				industry:'打家劫舍',
				join_date:'2000-9-01',
				leave_date:'2010-8-31',
				job_scope:'吴用平生机巧聪明，曾读万卷经书。使两条铜链。吴用为晁盖献计，智取生辰纲，用药酒麻倒了杨志，夺了大名府梁中书送给蔡太师庆生的金银珠宝。宋江二打祝家庄失败；第三次攻打祝家庄时，吴用利用连环计攻克祝家庄。吴用在破连环马时，派时迁偷甲骗徐宁上了梁山。晁盖曾头市兵败后，吴用又假扮算命先生，在卢俊义家写下藏头反诗，将卢俊义也暂时骗上山。卢俊义回去后被陷害，将被处斩，石秀劫法场亦身陷北京城，吴用及时出计，先发无头帖子稳局势，又差时迁火烧翠云楼，并救出卢俊义、石秀。'}},
  educations_attributes:{first: {enter_school:'1997-9-1',
	  			leave_school:'2001-9-1',
				major:'法学硕士',
				degree:'本科',
				school:'南京大学'}}
  			)


e=User.create(
  title:		'入云龙',
  city:			'蓟州府',
  id:			10004,
  mobile:		13916310004,
  user_name:		'公孙胜',
  true_name:		'公孙胜',
  :avatar => File.open(File.join(Rails.root, 'app', 'assets','images','公孙胜.jpg')),
  email:		'gss@ls.com',
  password:		'11111111',
  password_confirmation:'11111111',
  user_type:		'求职者',
  base_salary:		'10000',
  month_num:		'13',
  bonus:		'50000',
  housing:		'10200',
  transport:		'56000',
  birthday:		'1978-9-11',
  stock:		'股票',
  stock_num:		'1000',
  summaries_attributes:	{first:{content:'吴学究说三阮撞筹 公孙胜应七星聚义公孙胜与晁盖等人智取了生辰纲，上了梁山。后梁山好汉劫江州法场，救出宋江后，他因思念母亲而下山回乡。'}},
  works_attributes:	{first: {title:'公孙胜',
	  			employer:'梁山',
				industry:'打家劫舍',
				join_date:'2000-9-01',
				leave_date:'2010-8-31',
				job_scope:'吴学究说三阮撞筹 公孙胜应七星聚义公孙胜与晁盖等人智取了生辰纲，上了梁山。后梁山好汉劫江州法场，救出宋江后，他因思念母亲而下山回乡。'}},
  educations_attributes:{first: {enter_school:'1997-9-1',
	  			leave_school:'2001-9-1',
				major:'法学硕士',
				degree:'本科',
				school:'南京大学'}}
  			)

f=User.create(
  title:		'大刀',
  city:			'蒲东',
  id:			10005,
  mobile:		13916310005,
  user_name:		'关胜',
  true_name:		'关胜',
  :avatar => File.open(File.join(Rails.root, 'app', 'assets','images','关胜.jpg')),
  email:		'gs@ls.com',
  password:		'11111111',
  password_confirmation:'11111111',
  user_type:		'求职者',
  base_salary:		'10000',
  month_num:		'13',
  bonus:		'50000',
  housing:		'10200',
  transport:		'56000',
  birthday:		'1978-9-11',
  stock:		'股票',
  stock_num:		'1000',
  summaries_attributes:	{first:{content:'关胜乃三国时名将关羽嫡传子孙'},
	                second:{content:'精通兵法，绰号“大刀”。'},
			third: {content:'熟读兵书，深通武艺'},
			fourth:{content:'担任蒲东巡检'}},
  works_attributes:	{first: {title:'大刀',
	  			employer:'梁山',
				industry:'打家劫舍',
				join_date:'2000-9-01',
				leave_date:'2010-8-31',
				job_scope:'',
				}},
  educations_attributes:{first: {enter_school:'1997-9-1',
	  			leave_school:'2001-9-1',
				major:'法学硕士',
				degree:'本科',
				school:'南京大学'}}
  			)


g=User.create(
  title:		'豹子头',
  city:			'汴梁',
  id:			10006,
  mobile:		13916310006,
  user_name:		'林冲',
  true_name:		'林冲',
  :avatar => File.open(File.join(Rails.root, 'app', 'assets','images','林冲.jpg')),
  email:		'lc@ls.com',
  password:		'11111111',
  password_confirmation:'11111111',
  user_type:		'求职者',
  base_salary:		'10000',
  month_num:		'13',
  bonus:		'50000',
  housing:		'10200',
  transport:		'56000',
  birthday:		'1978-9-11',
  stock:		'股票',
  stock_num:		'1000',
  summaries_attributes:	{first:{content:'仗义是林冲，为人最朴忠。'},
	                second:{content:'江湖驰闻望，慷慨聚英雄。'},
			third: {content:'身世悲浮梗，功名类转蓬。'},
			fourth:{content:'他年若得志，威镇泰山东！'}},
  works_attributes:	{first: {title:'豹子头',
	  			employer:'梁山',
				industry:'打家劫舍',
				join_date:'2000-9-01',
				leave_date:'2010-8-31',
				job_scope:'',
				}},
  educations_attributes:{first: {enter_school:'1997-9-1',
	  			leave_school:'2001-9-1',
				major:'法学硕士',
				degree:'本科',
				school:'南京大学'}}
  			)

h=User.create(
  title:		'霹雳火',
  city:			'开州',
  id:			10007,
  mobile:		13916310007,
  user_name:		'秦明',
  true_name:		'秦明',
  :avatar => File.open(File.join(Rails.root, 'app', 'assets','images','秦明.jpg')),
  email:		'qm@ls.com',
  password:		'11111111',
  password_confirmation:'11111111',
  user_type:		'求职者',
  base_salary:		'10000',
  month_num:		'13',
  bonus:		'50000',
  housing:		'10200',
  transport:		'56000',
  birthday:		'1978-9-11',
  stock:		'股票',
  stock_num:		'1000',
  summaries_attributes:	{first:{content:'现代读者关于秦明的争议，基本上集中在其让人难以理解的“被宋江害得家破人亡，却能迅速转而归顺宋江，而且死心塌地”一事上。原著中所说的理由之一“上界星辰契合”，对于现代人来说是“无稽之谈”；理由之二及之三“被他们软困”和“怕斗他们不过”便成了主要理由，因此现代点评者往往认为秦明的落草是十分无奈的举动，结合其“灭地竟无声”（容与堂百回本作“也作横亡人”）的悲惨结局，认为从中体现出秦明的梁山生涯是个悲剧。但也有人认为，宋江把花荣的妹妹嫁给秦明，才是让秦明甘愿归顺的最重要原因，因为从原文推断，慕容知府所杀的秦明“家小”，应该只有其妻，或最多加上其孩儿，并不包括更多的亲属。如果按照这种推断，则秦明是个对婚姻很随意的人，和前妻的感情其实也算不上好，从中更体现出了古代社会妇女的地位卑微。'}},
  works_attributes:	{first: {title:'霹雳火',
	  			employer:'梁山',
				industry:'打家劫舍',
				join_date:'2000-9-01',
				leave_date:'2010-8-31',
				job_scope:'秦明在《水浒传》中出场于“镇三山大闹青州道，霹雳火夜走瓦砾场”一回。宋江与花荣因被刘高陷害而被捕[2] ，镇三山黄信将二人押送青州途中，清风山燕顺、郑天寿、王英将二人劫走。黄信急忙派人把情况告诉青州慕容知府，慕容知府接到急报，便派人请青州指挥司总管本州兵马秦统制来商议军情重事。这秦统制便是秦明，书里介绍他是“山后开州”（一说今重庆开县，一说今辽宁省凤城市，一说今河南省濮阳市）人，出身军官世家，使一条狼牙棒，有万夫不当之勇，因为性格急躁，声若雷霆，绰号“霹雳火”。'}},
  educations_attributes:{first: {enter_school:'1997-9-1',
	  			leave_school:'2001-9-1',
				major:'法学硕士',
				degree:'本科',
				school:'南京大学'}}
  			)

i=User.create(
  title:		'双鞭',
  city:			'太原',
  id:			10008,
  mobile:		13916310008,
  user_name:		'呼延灼',
  true_name:		'呼延灼',
  :avatar => File.open(File.join(Rails.root, 'app', 'assets','images','呼延灼.jpeg')),
  email:		'hyzh@ls.com',
  password:		'11111111',
  password_confirmation:'11111111',
  user_type:		'求职者',
  base_salary:		'10000',
  month_num:		'13',
  bonus:		'50000',
  housing:		'10200',
  transport:		'56000',
  birthday:		'1978-9-11',
  stock:		'股票',
  stock_num:		'1000',
  summaries_attributes:	{first:{content:'呼延灼，是古典小说《水浒传》中人物。祖上是北宋河东开国名将呼延赞，家传钢鞭（一说铜鞭）之法，并以其惯用兵器“双鞭”闻名，有万夫不当之勇。'}},
  works_attributes:	{first: {title:'汝宁郡都统制',
	  			employer:'梁山',
				industry:'打家劫舍',
				join_date:'2000-9-01',
				leave_date:'2010-8-31',
				job_scope:'呼延灼原为汝宁郡都统制，当时梁山军队攻陷了高唐州，令朝中震惊，太尉高俅向宋徽宗推荐呼延灼为征寇大将，于是天子宣呼延灼面圣，并因其一表非凡而龙颜大喜，御赐了一匹踢雪乌骓予呼延灼坐骑。[2] 
				呼延灼引荐陈州团练使“百胜将”韩滔及颍州团练使“天目将”彭玘为正副先锋，共同讨伐梁山。[3] '}},
  educations_attributes:{first: {enter_school:'1997-9-1',
	  			leave_school:'2001-9-1',
				major:'法学硕士',
				degree:'本科',
				school:'南京大学'}}
			)
j=User.create(
  title:		'小李广',
  city:			'青州',
  id:			10009,
  mobile:		13916310009,
  user_name:		'花荣',
  true_name:		'花荣',
  :avatar => File.open(File.join(Rails.root, 'app', 'assets','images','花荣.jpeg')),
  email:		'hr@ls.com',
  password:		'11111111',
  password_confirmation:'11111111',
  user_type:		'求职者',
  base_salary:		'10000',
  month_num:		'13',
  bonus:		'50000',
  housing:		'10200',
  transport:		'56000',
  birthday:		'1978-9-11',
  stock:		'股票',
  stock_num:		'1000',
  summaries_attributes:	{first:{content:'手脚细而长，眼睛幼细，外貌清秀俊朗的美男子。原为清风寨武知寨，后为梁山泊马军八虎骑兼先锋使第一员，使一杆长枪，箭法拔群，是梁山好汉中箭法首屈一指。因此，有小李广外号之外，也有“银枪手”和“神箭将军”的美誉。'}},
  works_attributes:	{first: {title:'清风寨武知寨',
	  			employer:'梁山',
				industry:'打家劫舍',
				join_date:'2000-9-01',
				leave_date:'2010-8-31',
				job_scope:'花荣多次用其高超箭法建立奇功。在三打祝家庄一役中，花荣射落祝家庄的指挥灯，使祝家庄兵马自乱。梁山受招安后，花荣随宋江平定了辽国、田虎、王庆和方腊。征战田虎时，曾在盖州城下，连射田虎部下大将方琼、张翔、杨端等数人，敌军闻之丧胆；征战方腊大战睦州时，阵前一箭射死方腊国师“宝光如来”邓元觉。
				
				受招安后，花荣被封为应天府兵马统制。宋江被毒死后，花荣夜梦宋江，遂来楚州探视，与吴用一同自缢于宋江、李逵墓前。'}},
  educations_attributes:{first: {enter_school:'1997-9-1',
	  			leave_school:'2001-9-1',
				major:'法学硕士',
				degree:'本科',
				school:'南京大学'}}
)
k=User.create(
  title:		'柴进',
  city:			'沧州',
  id:			10010,
  mobile:		13916310010,
  user_name:		'柴进',
  true_name:		'柴进',
  :avatar => File.open(File.join(Rails.root, 'app', 'assets','images','柴进.jpeg')),
  email:		'cj@ls.com',
  password:		'11111111',
  password_confirmation:'11111111',
  user_type:		'求职者',
  base_salary:		'10000',
  month_num:		'13',
  bonus:		'50000',
  housing:		'10200',
  transport:		'56000',
  birthday:		'1978-9-11',
  stock:		'股票',
  stock_num:		'1000',
  summaries_attributes:	{first:{content:'仗义疏财，喜爱交结天下英雄，曾帮助过林冲、宋江、武松、杜迁、王伦、石勇、李逵等人。长得龙眉凤目，皓齿朱唇，三牙掩口髭须。[1] 因高唐州知府高廉的妻弟殷天锡仗势要夺柴进的叔父柴皇城的住宅，柴皇城以有朝廷发的“丹书铁券”保护，与其论理，竟被他殴打。柴皇城召其侄柴进回来，继续与之论理时 ，殷天锡又欲殴打柴进，李逵在旁愤极，将其杀死。高廉便将柴进拘捕入狱，将其打入死牢。梁山好汉为救柴进，起兵攻打高唐州，由李逵从高唐州大牢后的枯井中将其救出。[2] 柴进被救上梁山后，为山寨掌管钱粮头领。'}},
  works_attributes:	{first: {title:'掌管钱粮头领',
	  			employer:'梁山',
				industry:'打家劫舍',
				join_date:'2000-9-01',
				leave_date:'2010-8-31',
				job_scope:'柴进被救上梁山后，为山寨掌管钱粮头领。随宋江去东京看灯时，柴进簪花入禁院，从睿思殿的御屏上剜下了御书四大寇中“山东宋江”四字。受招安后，随宋江、卢俊义征讨辽国、田虎、王庆。征方腊时，柴进化名柯引带着燕青到方腊处做卧底，深得方腊信任，后来杀死方杰。'}},
  educations_attributes:{first: {enter_school:'1997-9-1',
	  			leave_school:'2001-9-1',
				major:'法学硕士',
				degree:'本科',
				school:'南京大学'}}
)

a.save!(:validate => false)
b.save!(:validate => false)
c.save!(:validate => false)
d.save!(:validate => false)
e.save!(:validate => false)
f.save!(:validate => false)
g.save!(:validate => false)
h.save!(:validate => false)
i.save!(:validate => false)
j.save!(:validate => false)
k.save!(:validate => false)
